package com.air_ticketing;

import java.util.ArrayList;

public class PassengerDetails {
    String passengerName;
    long mobileNo;
    int age;
    String passengerAddress;
    String passengerId;

    ArrayList details = new ArrayList();

////    PassengerDetails(String passengerName,String mobileNo,String age,String passengerAddress){
//        this.passengerAddress=passengerAddress;
//        this.passengerName=passengerName;
//        this.age = age;
//        this.mobileNo=mobileNo;
//        this.passengerId = "A12B3C";//this should be autogenerated
//    }
}
